spring:
  datasource:
    url: jdbc:mysql://39.101.170.150:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 39.101.170.150 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.tata.jiuye: info

logstash:
  host: 39.101.170.150

requestempleurl: https://www.xmzzhy.com:8085/


aliyun:
  oss:
    endpoint: oss-cn-zhangjiakou.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4FyMjpYjQTaWUqe1gq8p #LTAI4GDtsVifM5rns4rq3Yrr # 访问身份验证中用到用户标识
    accessKeySecret: i3tLJpZ4nQlgakk24fxAtUSyF4ntKK #MVPJwk2VlBf3q5sRV9J5VhBQpXFeGX # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: zzjyshop # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://www.xmzzhy.com:8082/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: jiuye/images/ # 上传文件夹路径前缀
