spring:
  application:
    name: jiuye-admin
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml
mybatis-plus:
  mapper-locations:
    - classpath*:dao/*.xml
    - classpath*:com/**/mapper/*.xml

  global-config:
    banner: false
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true    #开启驼峰
    ###显示SQL语句部分
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: jiuye-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: jiuye
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4G5J7xp9V8CTWY63x2ST # 访问身份验证中用到用户标识
    accessKeySecret: CjWWNZSQR29pDgVynn1SNbEDxiJuZG # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: vandi # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://39.101.188.199:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: jiuye/images/ # 上传文件夹路径前缀

minio:
  endpoint: http://192.168.3.101:9090 #MinIO服务所在地址
  bucketName: jiuye #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
