spring:
  application:
    name: tata-portal
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      max-file-size: 10MB   #上传文件大小
      max-request-size: 100MB  #单次请求大小限制

mybatis-plus:
  mapper-locations:
    - classpath*:dao/*.xml
    - classpath*:com/**/mapper/*.xml

  configuration:
    map-underscore-to-camel-case: true
    ###显示SQL语句部分
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: tata-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /product/**
      - /brand/**
      - /pay/**
      - /withdrawExamine/allWithdrawApplicationPage
      - /withdrawExamine/approve
# 自定义redis key
redis:
  database: mall
  key:
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时

# 消息队列定义
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue



aliyun:
  sms:
    regionid: "cn-hangzhou"
    accesskeyid: "LTAI4G5J7xp9V8CTWY63x2ST"
    secret: "CjWWNZSQR29pDgVynn1SNbEDxiJuZG"
    signname: "格知教育"
    templatecode: "SMS_196642878"

  oss:
    endpoint: oss-cn-zhangjiakou.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4GCrh51knZ4SviLLKZz3 #LTAI4GDtsVifM5rns4rq3Yrr # 访问身份验证中用到用户标识
    accessKeySecret: 4piBt8TqVFozqL8nd5rGyEWPurJPwl #MVPJwk2VlBf3q5sRV9J5VhBQpXFeGX # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: cscyimages # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://cyjyt.com:8082/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: jiuye/images/ # 上传文件夹路径前缀

umsmemberlevelname:
  vip: "VIP会员"
  deliverycenter: "配送中心"
  ordinarymember: "普通会员"

pmsproductcategoryname:
  memberrepurchase: "会员复购"


  # wechat Auth
auth:
  wechat:
    sessionHost: 'https://api.weixin.qq.com/sns/jscode2session'
    appId: 'wxdaa9fb4025511958'
    secret: '56bcec96c36b270da318979e4c41f8fc'
    grantType: 'authorization_code'

file:
  mac:
    path: ~/file/
    avatar: ~/avatar/
  linux:
    path: /home/eladmin/file/
    avatar: /home/eladmin/avatar/
  windows:
    path: C:\eladmin\file\
    avatar: C:\eladmin\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5



